import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { logStep } from "@/lib/observability/timing";

// Supabase's email links arrive in one of two shapes, depending on how
// the "Confirm signup" / "Reset Password" templates are configured in
// the Dashboard (Authentication → Email Templates):
//   - `?token_hash=...&type=...` — a self-contained OTP verified directly
//     against Supabase, with no dependency on browser/device state. This
//     is Supabase's own recommended shape for an SSR app exactly because
//     it still works when the link is opened on a different device/
//     browser than the one that requested it (very common for a
//     password-reset email — e.g. request on a laptop, open the email on
//     a phone) — the `code` shape below cannot survive that, since its
//     verifier only exists in the requesting browser's storage.
//   - `?code=...` — a PKCE code, exchanged for a session. Requires the
//     `code_verifier` generated by the *same browser* that originally
//     called supabase.auth.resetPasswordForEmail()/signUp() still being
//     present in its storage.
// Both are handled here rather than assuming one, since which shape
// actually arrives depends on Dashboard configuration this app's code
// can't see or control.
const VALID_OTP_TYPES = ["signup", "invite", "magiclink", "recovery", "email_change", "email"] as const;
type OtpType = (typeof VALID_OTP_TYPES)[number];

function isOtpType(value: string | null): value is OtpType {
  return (VALID_OTP_TYPES as readonly string[]).includes(value ?? "");
}

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");
  const tokenHash = searchParams.get("token_hash");
  const type = searchParams.get("type");

  // Used by the password-reset flow to land on /reset-password instead of
  // / after verification below (see resetPasswordForEmail's redirectTo in
  // app/forgot-password/page.tsx). Restricted to an in-app path — never
  // an absolute/protocol-relative URL — so a crafted ?next= can't turn
  // this into an open redirect.
  const next = searchParams.get("next");
  const safeNext = next && next.startsWith("/") && !next.startsWith("//") ? next : "/";

  const tag = `auth-callback:${Math.random().toString(36).slice(2, 8)}`;
  logStep(
    tag,
    `received — token_hash=${Boolean(tokenHash)}, type=${type ?? "none"}, code=${Boolean(code)}, next=${safeNext}`,
  );

  const supabase = await createClient();

  // Verifying the link necessarily establishes a session (that's how
  // verifyOtp/exchangeCodeForSession work) — but landing on /login means
  // this was a signup confirmation, where the point is only to prove the
  // email address, not to skip the manual login step. Sign back out before
  // redirecting there so the user still has to enter their credentials.
  async function redirectTo(destination: string) {
    if (destination === "/login") {
      await supabase.auth.signOut();
    }
    return NextResponse.redirect(`${origin}${destination}`);
  }

  if (tokenHash && isOtpType(type)) {
    const { error } = await supabase.auth.verifyOtp({ type, token_hash: tokenHash });
    if (!error) {
      logStep(tag, "verifyOtp succeeded");
      return redirectTo(safeNext);
    }
    logStep(tag, `verifyOtp FAILED — ${error.message}`);
  } else if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) {
      logStep(tag, "exchangeCodeForSession succeeded");
      return redirectTo(safeNext);
    }
    // Most common real-world cause: the link was opened in a different
    // browser/device than the one that requested it, so the matching
    // code_verifier isn't in this browser's storage — see the shape
    // comment above. Switching the Dashboard's email template to the
    // token_hash shape avoids this entirely.
    logStep(tag, `exchangeCodeForSession FAILED — ${error.message}`);
  } else {
    logStep(tag, "no recognized params — redirecting to /login");
  }

  return NextResponse.redirect(`${origin}/login`);
}
